orbs:
  aws-ecr: circleci/aws-ecr@6.0.0
version: 2.1

#コメント11
workflows:
  pushTest:
    jobs:
      - aws-ecr/build-and-push-image:
          name: 'build-test'
          repo: '${ECR_REPO}'
          tag: pushtest
            