orbs:
  aws-ecr: circleci/aws-ecr@6.0.0
version: 2.1

#コメント11
workflows:
  #ECRにイメージをpush
  push:
    jobs:
      - aws-ecr/build-and-push-image:
          name: 'build-and-push'
          repo: '${ECR_REPO}'
          tag: '${REPO_TAG}'
            