version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.0.0

  workflows:
  build&push:
    jobs:
      - aws-ecr/build-and-push-image
          name: 'buid-test'
          repo: '${ECR_REPO}'
          tag: pushTest
          